### ISSUE TITLE
Switch the python binding to the most functioning python package

### ISSUE THREAD

**Issue by s-zeng** [dhall-lang/awesome-dhall#23]
Currently, the linked [dhall-python](https://github.com/SupraSummus/dhall-python) does not offer a complete implementation of Dhall, nor is it available on PyPI. I suggest we replace with [the one I maintain](https://github.com/s-zeng/dhall-python) instead, which offers full support (thanks to dhall-rust), and has better ux w.r.t. to packaging, installation, and use. Let me know what you think

**Comment by Gabriella439** [comment]
@s-zeng: Yeah, I think that's a good idea.  I have a PR up to change the link: https://github.com/dhall-lang/awesome-dhall/pull/26
