### ISSUE TITLE
Help with repo maintenance?

### ISSUE THREAD

**Issue by kukimik** [dhall-lang/awesome-dhall#39]
Perhaps I can help with the maintenance of this repo? There is some Dhall code lying around and adding links here could improve its discoverability. However, adding these projects one by one by separate PRs and managing the conflicts is a chore (and reviewing and merging them probably isn't much fun for @Gabriella439). If I was given the commit rights I would be happy to expand the list a bit at a leisurely pace, and handle the incoming PRs.

**Comment by Gabriella439** [comment]
I added you as a maintainer

**Comment by kukimik** [comment]
@Gabriella439 Can you resend the invitation to collaborate? I didn't get an email notification or missed it somehow, and now the invitation has expired.

**Comment by Gabriella439** [comment]
No worries!  I sent a new invitation

**Comment by kukimik** [comment]
Invitation accepted. Thanks!

**Comment by Gabriella439** [comment]
You're welcome!
